// PDF Export Utility
// Uses jsPDF for PDF generation

import jsPDF from 'jspdf';
import 'jspdf-autotable';

const pdfExport = {
    /**
     * Generate Tax Report PDF
     */
    async generateTaxReport({ region, fy, summary, formatCurrency }) {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;

        // Title
        doc.setFontSize(20);
        doc.setTextColor(40);
        doc.text('Tax Report', pageWidth / 2, 20, { align: 'center' });

        // FY and Region
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text(`${region} - ${fy.year}`, pageWidth / 2, 30, { align: 'center' });

        // Summary Section
        let yPos = 45;
        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text('Summary', 14, yPos);

        yPos += 10;
        doc.setFontSize(10);
        doc.setTextColor(60);

        const summaryData = [
            ['Total Income', formatCurrency(summary.totalIncome)],
            ['Tax Deductible Expenses', formatCurrency(summary.totalDeductible)],
            ['Non-Deductible Expenses', formatCurrency(summary.totalNonDeductible)],
            ['Estimated Taxable Income', formatCurrency(summary.taxableIncome)],
            ['Capital Gains', formatCurrency(summary.totalCapitalGains)]
        ];

        doc.autoTable({
            startY: yPos,
            head: [['Category', 'Amount']],
            body: summaryData,
            theme: 'grid',
            headStyles: { fillColor: [0, 120, 212] },
            margin: { left: 14 }
        });

        // Deductible Expenses Breakdown
        yPos = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text('Tax Deductible Expenses', 14, yPos);

        yPos += 10;
        const deductibleData = Object.entries(summary.deductibleByCategory || {}).map(([cat, data]) => [
            cat,
            data.count,
            formatCurrency(data.total)
        ]);

        if (deductibleData.length > 0) {
            doc.autoTable({
                startY: yPos,
                head: [['Category', 'Transactions', 'Total']],
                body: deductibleData,
                theme: 'striped',
                headStyles: { fillColor: [255, 165, 0] },
                margin: { left: 14 }
            });
        } else {
            doc.setFontSize(10);
            doc.text('No deductible expenses found', 14, yPos);
        }

        // Capital Gains (if any)
        if (summary.capitalGains && summary.capitalGains.length > 0) {
            yPos = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : yPos + 10;

            // Add new page if needed
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFontSize(14);
            doc.setTextColor(40);
            doc.text('Capital Gains', 14, yPos);

            yPos += 10;
            const cgData = summary.capitalGains.map(cg => [
                cg.symbol,
                formatCurrency(cg.gain),
                `${cg.gainPercent.toFixed(2)}%`,
                cg.type,
                cg.taxRate
            ]);

            doc.autoTable({
                startY: yPos,
                head: [['Stock', 'Gain/Loss', '%', 'Type', 'Tax Rate']],
                body: cgData,
                theme: 'grid',
                headStyles: { fillColor: [34, 139, 34] },
                margin: { left: 14 }
            });
        }

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(
                `Generated by PocketWall - Page ${i} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            );
        }

        // Save
        doc.save(`TaxReport_${region}_${fy.year}.pdf`);
    },

    /**
     * Generate Investment Performance Report PDF
     */
    async generateInvestmentReport({ performanceData, allocationData, formatCurrency }) {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;

        // Title
        doc.setFontSize(20);
        doc.setTextColor(40);
        doc.text('Investment Performance Report', pageWidth / 2, 20, { align: 'center' });

        // Date
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });

        // Summary Section
        let yPos = 40;
        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text('Portfolio Summary', 14, yPos);

        yPos += 10;
        const summaryData = [
            ['Total Invested', formatCurrency(performanceData.totalInvested)],
            ['Current Value', formatCurrency(performanceData.totalCurrentValue)],
            ['Absolute Returns', formatCurrency(performanceData.totalGain)],
            ['Returns %', `${performanceData.totalGainPercent.toFixed(2)}%`],
            ['Portfolio CAGR', `${performanceData.portfolioCAGR.toFixed(2)}%`]
        ];

        doc.autoTable({
            startY: yPos,
            head: [['Metric', 'Value']],
            body: summaryData,
            theme: 'grid',
            headStyles: { fillColor: [0, 120, 212] },
            margin: { left: 14 }
        });

        // Best/Worst Performers
        yPos = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text('Top Performers', 14, yPos);

        yPos += 10;
        if (performanceData.bestPerformer && performanceData.worstPerformer) {
            const performersData = [
                [
                    '🏆 Best',
                    performanceData.bestPerformer.symbol,
                    `+${performanceData.bestPerformer.gainPercent.toFixed(2)}%`,
                    `${performanceData.bestPerformer.cagr.toFixed(2)}%`
                ],
                [
                    '📉 Worst',
                    performanceData.worstPerformer.symbol,
                    `${performanceData.worstPerformer.gainPercent.toFixed(2)}%`,
                    `${performanceData.worstPerformer.cagr.toFixed(2)}%`
                ]
            ];

            doc.autoTable({
                startY: yPos,
                head: [['Rank', 'Stock', 'Return %', 'CAGR']],
                body: performersData,
                theme: 'striped',
                headStyles: { fillColor: [34, 139, 34] },
                margin: { left: 14 }
            });
        }

        // Stock-wise Performance
        yPos = doc.lastAutoTable.finalY + 15;

        // Add new page if needed
        if (yPos > 240) {
            doc.addPage();
            yPos = 20;
        }

        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text('Stock-wise Performance', 14, yPos);

        yPos += 10;
        const stockData = performanceData.stockPerformance.map(sp => [
            sp.symbol,
            formatCurrency(sp.invested),
            formatCurrency(sp.current),
            `${sp.gainPercent >= 0 ? '+' : ''}${sp.gainPercent.toFixed(2)}%`,
            `${sp.cagr.toFixed(2)}%`
        ]);

        doc.autoTable({
            startY: yPos,
            head: [['Stock', 'Invested', 'Current', 'Return %', 'CAGR']],
            body: stockData,
            theme: 'grid',
            headStyles: { fillColor: [0, 120, 212] },
            margin: { left: 14 },
            columnStyles: {
                1: { halign: 'right' },
                2: { halign: 'right' },
                3: { halign: 'right' },
                4: { halign: 'right' }
            }
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(
                `Generated by PocketWall - Page ${i} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            );
        }

        // Save
        doc.save(`InvestmentReport_${new Date().toISOString().slice(0, 10)}.pdf`);
    },

    /**
     * Generate Monthly Report PDF (existing function placeholder)
     */
    async generateMonthlyReport(data) {
        const doc = new jsPDF();
        // ... existing implementation
        doc.save('MonthlyReport.pdf');
    }
};

export default pdfExport;
